# Match config
START_ON_THE_RIGHT = True
WE_HAVE_BEACONS    = True
ENNEMY_HAS_BEACONS = False

# Add obstacles to simulate people around the table
JEAN_MICHEL_CASSE_COUILLES = True
# People are squares with the size defined bellow
JEAN_MICHEL_WIDTH = 100

ENABLE_FAST_GRAPHICS = True

# Hardware config
LIDAR_POINTS_PER_TURN  = 400
LIDAR_ROTATE_CLOCKWISE = True

LIDAR_ANGLE_ERROR = 0
LIDAR_DISTANCE_ERROR = 0
LIDAR_ANGLE_ERROR = 0.5
LIDAR_DISTANCE_ERROR = 0.02 # 2% resolution


# Graphic constant
PIXEL_PER_METER = 200

TABLE_WIDTH  = 3000
TABLE_HEIGHT = 2000

WINDOW_WIDTH  = 1800
WINDOW_HEIGHT = 900

TABLE_CENTER = (-350, 0)
